//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantaF1_SVRKEntities : DbContext
    {
        public FantaF1_SVRKEntities()
            : base("name=FantaF1_SVRKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CampionatiMondiali> CampionatiMondiali { get; set; }
        public virtual DbSet<Circuiti> Circuiti { get; set; }
        public virtual DbSet<FantaCampionati> FantaCampionati { get; set; }
        public virtual DbSet<IscrizioniCircuitiCampionato> IscrizioniCircuitiCampionato { get; set; }
        public virtual DbSet<IscrizioniPilotiCampionato> IscrizioniPilotiCampionato { get; set; }
        public virtual DbSet<IscrizioniScuderieCampionato> IscrizioniScuderieCampionato { get; set; }
        public virtual DbSet<IscrizioniUtentiFantaCampionato> IscrizioniUtentiFantaCampionato { get; set; }
        public virtual DbSet<Piloti> Piloti { get; set; }
        public virtual DbSet<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato { get; set; }
        public virtual DbSet<PronosticoUtenteGara> PronosticoUtenteGara { get; set; }
        public virtual DbSet<RegoleCampionatoMondiale> RegoleCampionatoMondiale { get; set; }
        public virtual DbSet<RegoleFantaCampionato> RegoleFantaCampionato { get; set; }
        public virtual DbSet<RisultatoDFNGaraReale> RisultatoDFNGaraReale { get; set; }
        public virtual DbSet<RisultatoGaraReale> RisultatoGaraReale { get; set; }
        public virtual DbSet<RisultatoPronostico> RisultatoPronostico { get; set; }
        public virtual DbSet<Scuderie> Scuderie { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<IscrizioniPilotiScuderie> IscrizioniPilotiScuderie { get; set; }
    }
}
