//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IscrizioniCircuitiCampionato
    {
        public int Id { get; set; }
        public int CircuitoId { get; set; }
        public int CampionatoId { get; set; }
        public Nullable<int> RisultatiId { get; set; }
        public System.DateTime DataGara { get; set; }
        public string NomeGP { get; set; }
    
        public virtual CampionatiMondiali CampionatiMondiali { get; set; }
        public virtual Circuiti Circuiti { get; set; }
        public virtual RisultatoGaraReale RisultatoGaraReale { get; set; }
    }
}
