//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IscrizioniPilotiScuderie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IscrizioniPilotiScuderie()
        {
            this.IscrizioniPilotiCampionato = new HashSet<IscrizioniPilotiCampionato>();
        }
    
        public int Id { get; set; }
        public int PilotaId { get; set; }
        public int ScuderiaId { get; set; }
        public System.DateTime DataInizioContratto { get; set; }
        public System.DateTime DataFineContratto { get; set; }
    
        public virtual Piloti Piloti { get; set; }
        public virtual Scuderie Scuderie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IscrizioniPilotiCampionato> IscrizioniPilotiCampionato { get; set; }
    }
}
