//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IscrizioniUtentiFantaCampionato
    {
        public int Id { get; set; }
        public int UtenteId { get; set; }
        public int CampionatoId { get; set; }
        public int PronosticoCampionatoId { get; set; }
        public int PunteggioCampionatoMondiale { get; set; }
        public System.DateTime DataPronosticoMondiale { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
