//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IscrizioniUtentiFantaCampionato
    {
        public int Id { get; set; }
        public int UtenteId { get; set; }
        public int CampionatoId { get; set; }
        public int PronosticoCampionatoId { get; set; }
        public int PunteggioCampionatoMondiale { get; set; }
        public System.DateTime DataPronosticoMondiale { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
