//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piloti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Piloti()
        {
            this.IscrizioniPilotiCampionato = new HashSet<IscrizioniPilotiCampionato>();
            this.RisultatoDFNGaraReale = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale1 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale1 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale2 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale2 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale3 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale3 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale4 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale4 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale5 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale5 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale6 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale6 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale7 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale7 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale8 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale8 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale9 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale9 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale10 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale10 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale11 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale11 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale12 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale12 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale13 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale13 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale14 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale14 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale15 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale15 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale16 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale16 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale17 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale17 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale18 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale18 = new HashSet<RisultatoGaraReale>();
            this.RisultatoDFNGaraReale19 = new HashSet<RisultatoDFNGaraReale>();
            this.RisultatoGaraReale19 = new HashSet<RisultatoGaraReale>();
            this.RisultatoGaraReale20 = new HashSet<RisultatoGaraReale>();
            this.RisultatoGaraReale21 = new HashSet<RisultatoGaraReale>();
            this.PronosticoUtenteFantaCampionato = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato1 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato2 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato3 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato4 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato5 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato6 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato7 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato8 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteFantaCampionato9 = new HashSet<PronosticoUtenteFantaCampionato>();
            this.PronosticoUtenteGara = new HashSet<PronosticoUtenteGara>();
            this.PronosticoUtenteGara1 = new HashSet<PronosticoUtenteGara>();
            this.PronosticoUtenteGara2 = new HashSet<PronosticoUtenteGara>();
            this.PronosticoUtenteGara3 = new HashSet<PronosticoUtenteGara>();
            this.PronosticoUtenteGara4 = new HashSet<PronosticoUtenteGara>();
            this.PronosticoUtenteGara5 = new HashSet<PronosticoUtenteGara>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public int ScuderiaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IscrizioniPilotiCampionato> IscrizioniPilotiCampionato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoDFNGaraReale> RisultatoDFNGaraReale19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisultatoGaraReale> RisultatoGaraReale21 { get; set; }
        public virtual Scuderie Scuderie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteFantaCampionato> PronosticoUtenteFantaCampionato9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteGara> PronosticoUtenteGara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteGara> PronosticoUtenteGara1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteGara> PronosticoUtenteGara2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteGara> PronosticoUtenteGara3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteGara> PronosticoUtenteGara4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PronosticoUtenteGara> PronosticoUtenteGara5 { get; set; }
    }
}
