//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PronosticoUtenteFantaCampionato
    {
        public int Id { get; set; }
        public int PrimoClassificatoPilotaId { get; set; }
        public int SecondoClassificatoPilotaId { get; set; }
        public int TerzoClassificatoPilotaId { get; set; }
        public int QuartoClassificatoPilotaId { get; set; }
        public int QuintoClassificatoPilotaId { get; set; }
        public int SestoClassificatoPilotaId { get; set; }
        public int SettimoClassificatoPilotaId { get; set; }
        public int OttavoClassificatoPilotaId { get; set; }
        public int NonoClassificatoPilotaId { get; set; }
        public int DecimoClassificatoPilotaId { get; set; }
        public int PrimaClassificataScuderiaId { get; set; }
        public int SecondaClassificataScuderiaId { get; set; }
        public int TerzaClassificataScuderiaId { get; set; }
        public int QuartaClassificataScuderiaId { get; set; }
        public int QuintaClassificataScuderiaId { get; set; }
        public int SestaClassificataScuderiaId { get; set; }
        public int SettimaClassificataScuderiaId { get; set; }
        public int OttavaClassificataScuderiaId { get; set; }
        public int NonaClassificataScuderiaId { get; set; }
        public int DecimaClassificataScuderiaId { get; set; }
    
        public virtual Piloti Piloti { get; set; }
        public virtual Piloti Piloti1 { get; set; }
        public virtual Piloti Piloti2 { get; set; }
        public virtual Piloti Piloti3 { get; set; }
        public virtual Piloti Piloti4 { get; set; }
        public virtual Piloti Piloti5 { get; set; }
        public virtual Piloti Piloti6 { get; set; }
        public virtual Piloti Piloti7 { get; set; }
        public virtual Piloti Piloti8 { get; set; }
        public virtual Piloti Piloti9 { get; set; }
        public virtual Scuderie Scuderie { get; set; }
        public virtual Scuderie Scuderie1 { get; set; }
        public virtual Scuderie Scuderie2 { get; set; }
        public virtual Scuderie Scuderie3 { get; set; }
        public virtual Scuderie Scuderie4 { get; set; }
        public virtual Scuderie Scuderie5 { get; set; }
        public virtual Scuderie Scuderie6 { get; set; }
        public virtual Scuderie Scuderie7 { get; set; }
        public virtual Scuderie Scuderie8 { get; set; }
        public virtual Scuderie Scuderie9 { get; set; }
    }
}
