//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegoleFantaCampionato
    {
        public int Id { get; set; }
        public int PunteggioPrimoClassificato { get; set; }
        public int PunteggioSecondoClassificato { get; set; }
        public int PunteggioTerzoClassificato { get; set; }
        public int PunteggioGiroVeloce { get; set; }
        public int PunteggioPolePosition { get; set; }
        public int PunteggioDFN { get; set; }
        public bool ComboPodio { get; set; }
        public bool ComboTotale { get; set; }
        public int PunteggioPodio { get; set; }
        public int PunteggioTotale { get; set; }
        public int PunteggioPrimoPilotaMondiale { get; set; }
        public int PunteggioSecondoPilotaMondiale { get; set; }
        public int PunteggioTerzoPilotaMondiale { get; set; }
        public int PunteggioQuartoPilotaMondiale { get; set; }
        public int PunteggioQuintoPilotaMondiale { get; set; }
        public int PunteggioSestoPilotaMondiale { get; set; }
        public int PunteggioSettimoPilotaMondiale { get; set; }
        public int PunteggioOttavoPilotaMondiale { get; set; }
        public int PunteggioNonoPilotaMondiale { get; set; }
        public int PunteggioDecimoPilotaMondiale { get; set; }
        public int PunteggioPrimaScuderiaMondiale { get; set; }
        public int PunteggioSecondaScuderiaMondiale { get; set; }
        public int PunteggioTerzaScuderiaMondiale { get; set; }
        public int PunteggioQuartaScuderiaMondiale { get; set; }
        public int PunteggioQuintaScuderiaMondiale { get; set; }
        public int PunteggioSestaScuderiaMondiale { get; set; }
        public int PunteggioSettimaScuderiaMondiale { get; set; }
        public int PunteggioOttavaScuderiaMondiale { get; set; }
        public int PunteggioNonaScuderiaMondiale { get; set; }
        public int PunteggioDecimaScuderiaMondiale { get; set; }
        public int PunteggioMalusCambioPronosticoMondiale { get; set; }
        public Nullable<int> PunteggioPrimoPilotaSprintRace { get; set; }
    }
}
