//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantaF1DataAccessDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RisultatoPronostico
    {
        public int Id { get; set; }
        public int PronosticoId { get; set; }
        public bool RisultatoPrimoClassificato { get; set; }
        public bool RisultatoSecondoClassificato { get; set; }
        public bool RisultatoTerzoClassificato { get; set; }
        public bool RisultatoPolePosition { get; set; }
        public bool RisultatoGiroVeloce { get; set; }
        public bool RisultatoDFN { get; set; }
        public int PunteggioComplessivoPronostico { get; set; }
        public Nullable<bool> PunteggioPrimoClassificatoSprintRace { get; set; }
    
        public virtual PronosticoUtenteGara PronosticoUtenteGara { get; set; }
    }
}
